### ISSUE TITLE
needs a whitelist

### ISSUE THREAD

**Issue by atomGit** [jingyu9575/service-worker-control#1]
interesting extension, but i think it would be more useful (and less hassle) if it kept and editable whitelist of domains, including subdomains

**Comment by jingyu9575** [comment]
I've thought about this but did not come up with a good design.
What's your use case? Right now I allow the service workers in the popup and it will keep registered in the browser. For other sites, I simply ignore the request icon. Therefore I do not need whitelists or blacklists.

**Comment by atomGit** [comment]
the use case is for sites that require workers to function, such as regex101.com - in such cases, it would be more convenient to whitelist the domains rather than having to manually allow workers every time they're visited

**Comment by jingyu9575** [comment]
There is no need to allow every time; once the service worker is allowed, it will keep registered, until it is manually removed.
Are you clearing site data periodically?

**Comment by atomGit** [comment]
i mean across sessions

**Comment by jingyu9575** [comment]
Service workers are not removed when Firefox restarts. Check about:debugging for the registrations.

**Comment by atomGit** [comment]
the problem here is mass confusion on my part i think :)

i use Site Bleacher to remove workers (and other storage), uMatrix to allow/disallow workers, and i'm confusing part of their functionality with that of your extension

what i was wanting to do is whitelist workers globally in uMatrix and control whether they load with your extension, but i think i was forgetting about Site Bleacher which i can't give up because it's the only ext. that dumps indexedDB storage automatically (upon revisiting the domain) and you can't disable its worker cleaning

sorry for the trouble

**Comment by jingyu9575** [comment]
In this case I think the whitelist has to be in Site Bleacher. Even if my extension whitelists everything, after Site Bleacher clears the service workers, the functionalities such as offline loading of regex101.com will still not work.
