### ISSUE TITLE
pop-up notification not appearing

### ISSUE THREAD

**Issue by atomGit** [jingyu9575/service-worker-control#2]
i'm not seeing [this](https://addons.cdn.mozilla.net/user-media/previews/full/218/218906.png?modified=1557153175) - the notify option is enabled and i just quickly tested on YouTube - the icon appears in the address bar, but no pop-up

**Comment by jingyu9575** [comment]
It shows after clicking the icon. Unfortunately automatically showing this popup is not supported by WebExtensions.

**Comment by atomGit** [comment]
gotchya - thanks
