### ISSUE TITLE
Push notification history duplicating entries

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [jingyu9575/service-worker-control#5]
I don't know if it was coded to act this way, but they are adding two of the same entry on push notification history.

https://i.imgur.com/joQXvS5.png

Another question: is there a way to add a icon on toolbar to facilitate access to this option?

**Comment by jingyu9575** [comment]
> two of the same entry on push notification history

It's not intended. I've tested earlier but both the websites in the screenshot do not work on my system. I'll try again later.

Edit: rapaduratech.com.br works now in a new profile after fixing a bug. I'll wait for notifications.

> add a icon on toolbar

It is possible, but one extension can only add one icon. I think the notification history is not the primary feature of this extension, and if I add some UI later like management of all registered service workers, there will be no icon left to open that.

I think it is better to create another extension that add the icon. Would you mind installing another extension to get the icon?

**Comment by KlausEverWalkingDev** [comment]
Thanks for your reply :) I wouldn't mind have another tiny extension for that "feature". And in the future when you improve the power of Service Worker Control, you can merge both in one. :) Thanks again :)

**Comment by jingyu9575** [comment]
[Service Worker Control - Push Notification History](https://addons.mozilla.org/addon/swcontrol-notification-history/)

The main extension also needs to be updated.

**Comment by KlausEverWalkingDev** [comment]
It worked great! Thanks! Is a by-design limitation of Service Workers that you only can add (accept) them when they ask to? Any reason to not work like popups and scripts?

**Comment by jingyu9575** [comment]
> you only can add (accept) them when they ask to? Any reason to not work like popups and scripts?

I'm not sure I understand your question, but Service Workers are scripts provided by websites, and opened websites can choose to register them at any time. What's the difference with popups and scripts?

**Comment by KlausEverWalkingDev** [comment]
For example, Service Workers being scripts already loaded with the page, could not this extension force them to show up to be accepted/denied? I mean, if not blocked, popups and other scripts run automatically with no consent of the user, right?

**Comment by jingyu9575** [comment]
Yes the extension can require consent to register service workers. It needs to be enabled in the options.

![screenshot](https://addons.cdn.mozilla.net/user-media/previews/full/218/218906.png?modified=1557153175)

However, the icon must be manually clicked, because Firefox does not allow extensions to show this panel without clicking.

**Comment by KlausEverWalkingDev** [comment]
Oh, I see. Now I got it :) Thanks and sorry for the annoying questions. Keep it up. :)

**Comment by jingyu9575** [comment]
> two of the same entry on push notification history

Fixed in 1.2. The new script comes into effect when the service workers are re-registered (visiting the website with last registration >24h old).
