### ISSUE TITLE
Icon not adapting to Windows 10 dark mode? (Firefox 70)

### ISSUE THREAD

**Issue by sprite-1** [jingyu9575/service-worker-control#7]
On Firefox 70, the icons for both Service Worker Control and Service Worker Control - Push Notification History don't seem to respect Windows 10's dark mode

![image](https://user-images.githubusercontent.com/33685433/68863118-b0d4a180-0729-11ea-87a5-37c96316e98c.png)

**Comment by jingyu9575** [comment]
The color is correct on my system:

![图片](https://user-images.githubusercontent.com/8923139/69290905-b4709880-0c01-11ea-9781-d4086c49e10c.png)

Try setting `svg.context-properties.content.enabled` to `true` in about:config.

**Comment by sprite-1** [comment]
Setting `svg.context-properties.content.enabled` to `true` only fixed the **Service Worker Control - Push Notification History** icon, but the **Service Worker Control** is still black

**Comment by jingyu9575** [comment]
I'm not sure what is happening. I tried on Firefox 70.0.1 with a new profile, and the icon in the address bar was already light when I first installed the extension.

![图片](https://user-images.githubusercontent.com/8923139/69904862-a9a9c680-13ac-11ea-8cc8-62810e6c291e.png)

I'm using the built-in dark theme. Are you using this theme? Are there any other customizations on your browser?

**Comment by sprite-1** [comment]
Oh crap I'm terribly sorry! I got the two mixed up! The Push Notification History is the one that isn't turning light. The main addon works as it should.

![image](https://user-images.githubusercontent.com/33685433/69909632-e02d2300-1438-11ea-9a0b-99b1df320012.png)

Sorry again for the confusion!

**Comment by jingyu9575** [comment]
I just tested again. On my system, this icon is controlled by `svg.context-properties.content.enabled`:

![MLkQ3yIKc1](https://user-images.githubusercontent.com/8923139/69913707-9a258e80-143b-11ea-9daa-84f275aa9f02.gif)

I'm not sure what is happening here. Is it still black after restarting Firefox?

**Comment by sprite-1** [comment]
Well... I just ended up going with the nuclear method and wiped my Firefox profile completely and it works properly now so I guess the issue can be closed now
